zuul:
  prefix: /api 
  routes:
    simple:
      path: /simple/**
      serviceId: SimpleService
    other:
      path: /discovery/**
      serviceId: DiscoveryService
      
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    
server:  port: 0
            